### ISSUE TITLE
HEX <-> ASCII string conversion

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#13]
Just working on script parsing received network packet and miss such function.... There are [number of ways](https://stackoverflow.com/questions/47750732/write-hex-values-to-file-in-windows-batch/47826309#47826309), but "native" solution will be nice.

**Comment by adoxa** [comment]
Please provide a whole lot more detail.

**Comment by lazna** [comment]
Want to manage network device and do not known its IP address, but fortunatelly the device support "discovery protocol". When I sent specific data to network broadcast (address 255.255.255.255) the device reply by packet containing informations about it, including IP address and netmask.

For network communication utilizing [PacketSender](https://packetsender.com/documentation) console interface which print HEX formated responses into STDOUT. Than I processing packet by shell script , extract address/mask pair, computate free IP address on given subnet, set it on specicific network interface utilizing 'netsh' and start browser on IP address of device HTTP management or perform another script operation utilizing telnet os SSH console clients like FW upgrade, etc...

For packet decoding will be nice to have functions like:

hex2dec (now 'set /a out=0xhexnum' or [sysinternals](https://docs.microsoft.com/en-us/sysinternals/downloads/hex2dec))
hex2ascii (now loading ascii table as a serie of variables into memory on each script startup, than looping throung packet single HEX and evaluating) 

and possibly vice versa (??)

**Comment by adoxa** [comment]
Is using Packet Sender's ASCII response not an option?

Converting a single number to decimal is fine as is, but I'm not sure about converting to hex. Still, I could add `dec` and `hex` variable modifiers (and probably `oct` and `bin`, or maybe just `base[N]`), or perhaps do them as part of the new calculator.

`Call` can't return a string, so for a list I would use something like `set $hex=@hexlify[ascii string]` and `set $ascii=@unhexlify[$hex]`. Or, given it's likely to be in variables, `set $hex=%$ascii;hexlify%` and `set $ascii=%$hex;unhexlify%` might be better. Or even go with call, after all: `call @hexlify $hex "ascii string"` and `call @unhexlify $ascii "hex string"`. So if it's only ever expected to be in variables go with the modifier, otherwise the call.

It's not actually ASCII, though, which could cause issues with 80-FF; you'd probably need to set code page 28591 for writing to file. 00 is also problematic, as everything still uses that for string termination.

**Comment by lazna** [comment]
> Is using Packet Sender's ASCII response not an option?

Totally unreliable, as it dont know anything about the packet structure, it just guessing what digit is simple ascii character and what is a part of HEX16 encoded number....

> Converting a single number to decimal is fine as is, but I'm not sure about converting to hex. Still, I could add `dec` and `hex` variable modifiers (and probably `oct` and `bin`, or maybe just `base[N]`), or perhaps do them as part of the new calculator.
> 
> `Call` can't return a string, so for a list I would use something like `set $hex=@hexlify[ascii string]` and `set $ascii=@unhexlify[$hex]`. Or, given it's likely to be in variables, `set $hex=%$ascii;hexlify%` and `set $ascii=%$hex;unhexlify%` might be better. Or even go with call, after all: `call @hexlify $hex "ascii string"` and `call @unhexlify $ascii "hex string"`. So if it's only ever expected to be in variables go with the modifier, otherwise the call.

By me, variable is fine.

> It's not actually ASCII, though, which could cause issues with 80-FF; you'd probably need to set code page 28591 for writing to file. 00 is also problematic, as everything still uses that for string termination.

I am talking about printable ascii only...

**Comment by adoxa** [comment]
> By me, variable is fine.

That would be my preference (thus if you want a fixed string place it in a variable first).

> I am talking about printable ascii only...

You might be, but you can bet there'll be someone who'll see "hex" and think "binary".

**Comment by lazna** [comment]
> > I am talking about printable ascii only...
> 
> You might be, but you can bet there'll be someone who'll see "hex" and think "binary".

;-)

**Comment by adoxa** [comment]
So, let's get to the nitty-gritty.

What should `hexlify` produce? Initially I was thinking only straight hex, but a space separating bytes would be easier for human viewing (if that's necessary); a comma could be useful for CSV. I think just generating upper case digits is okay, the existing `lower` modifier can be used if you prefer lower case. Thus `hexlify` generates a spaceless string (or is space a better default?) and `hexlify[?]` generates a `?`-separated string (`[]` for no space). Maybe even get fancy: `hexlify[ 4-]` generates a dash every fourth byte, space otherwise.

I was going to be more strict with `unhexlify`: any invalid letter, or an odd number of digits, would result in an error (variable remains unchanged). I'm not sure about separators: should any punctuation (i.e. any non-alphanumeric) be allowed, or just a select few? If it's just a few, `hexlify` should only allow those, too.

Actually, maybe just space is enough and use the existing substitution mechanism to remove/replace as you like. Miss out on fancy, but keeps it simple.

```batch
> set $ascii=a string
> echo %$ascii;hexlify%
61 20 73 74 72 69 6E 67
> echo %$ascii;hexlify: =%
6120737472696E67
```

That means the hex string could potentially be separated by anything, but it still might be best for `unhexlify` to only recognise a select few. Packet Sender has ` ,.;:x\n\r\t` and `0x`; I would add `-` (maybe `_`?), drop `x` and `0x` (maybe not?), and use `isspace` instead of individual characters.

**Comment by lazna** [comment]
In addition to discussed HEX coding: When using batch files as a CGI, often dealing with [URL Encoding](https://en.wikipedia.org/wiki/Percent-encoding) which is a bit complicated by fact the percent sign is used. But including this with the new HEX coding functions will be very usefull too. But not sure how about unicode, because I am working on non-english environment.

**Comment by adoxa** [comment]
Separate encoding, separate issue. (Convert Unicode to UTF-8, encode the resulting bytes.)

**Comment by lazna** [comment]
OK, creating new issue..

**Comment by adoxa** [comment]
Commit 01e7703 adds `hexify` and `unhexify` modifiers (dropped the `l`); see the commit message for details. BTW, there's no need to assign fixed strings to vars first, use the default value: `echo %;'68 65 78';unhexify%`.

**Comment by carlos-montiers** [comment]
> `echo %;'68 65 78';unhexify%`.

Really nice technique
