### ISSUE TITLE
Proposed error handling extensions

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#31]
`@errmsg` - Get the value of the most recent error message. This could be useful when stderr is redirected to nul, and also with my second request below.

`@onerror` - Get or Set a statement to be executed whenever an error is detected. Not sure exactly where the onerror action would be patched in, but presumably where you augment the error message with the executing script name and line number. I suppose there may be some complications with FOR /F ... IN('cmd') and/or with pipes - the `@onerror` action should probably not propagate to the child processes.

I think this feature could be extremely powerful when combined with [batch file exception handling](https://stackoverflow.com/a/31445372/1012053). Currently the exception handling is very powerful, but it requires that all exceptions be explicitly raised. The `@onerror` extension would allow automatic raising of exceptions via something like

    set "@onerror=call exception throw !errorlevel! "!@errmsg!" "!$0!:!@batchline!""

**Comment by adoxa** [comment]
I don't think `@errmsg` would be a problem (although it would never be cleared). I'll have to think more on `@onerror`.

**Comment by DaveBenham** [comment]
> I don't think `@errmsg` would be a problem (although it would never be cleared).

Is there some way you can detect when the ERRORLEVEL is set to 0 and clear `@errmsg`? If not, then a never cleared `@errmsg` would still be useful.

> I'll have to think more on `@onerror`.

Have a look at the exception handling I linked if you haven't already. It is really kind of shocking how well it works, and it might nudge you towards implementing `@onerror`.  It might even be possible to implement the features of the exception handling within EB. But the pure batch implementation works well enough - I just need a mechanism to automatically raise an exception upon error.

**Comment by adoxa** [comment]
> Is there some way you can detect when the ERRORLEVEL is set to 0 and clear `@errmsg`?

There is, but it's all done individually, so somewhat infeasible.

**Comment by DaveBenham** [comment]
I'm not surprised :(

**Comment by carlos-montiers** [comment]
the @onerror idea I think is related to provide a way of save anonymous blocks of code in variables. like the functions of bash, I thinked it could be implemented using "virtual files" (causing cmd read in that case from a buffer instead of a file) but maybe introduce new problems, I think related to the filename mainly, it not exist really in the operating system, thus is not possible get the attributes of it, or the full path.

What about an implementation of @onerror using a label:
set "@onerror=:handlerror"

and add a new command extension: RECOVER

thus:
```
set "@onerror=:handlerror"

:handlerror
echo !@errmsg!>>log.txt 2>nul
call @RECOVER // nothing happen
```

Thus if you not call to RECOVER the exception is raised.
The idea is inspired by the used in the golang: panic / recover

This also gives the idea of implement something like for raise exception with our messages:

```
call @PANIC "Is not possible divide by zero"
```

**Comment by DaveBenham** [comment]
No, that can't work, at least for my purposes, because the :handlerror label may be defined in script A, which calls script B (maybe a utility script that someone else wrote), and script B probably doesn't have the :handlerror label.

That is why in my design I put my exception error handling code in a standalone script that can be called from anywhere.

If you can force cmd to call or goto an arbitrary label, then I think it ought to be possible to generalize and execute most any code.

cmd already supports execution of simple code in a variable, as easy as storing the static command in macroVar, and then executing %macroVar% in the code. But I don't know what it takes to virtually execute the code without having %macroVar% in the physical script. If that can be done then I think the ability to run [sophisticated macros with parameters](https://www.dostips.com/forum/viewtopic.php?f=3&t=2518) would naturally follow.

**Comment by carlos-montiers** [comment]
Mmm, I think each script with EB loaded can have a own handler, thus if script B not handles a exception it can be handled by script A.
@adoxa Maybe is possible add the variable type function for store blocks of code and reference it as variables, maybe we can use something like we have with the function readBatchFile ?

**Comment by adoxa** [comment]
It sounds like you both want to go beyond what I want to do. Why this persistence in trying to make batch do things it's not designed for? Just use another language, already! (Okay, sure, it's very portable, but using EB breaks that portability, so save yourself (and me!) some heartache and use a *proper* language.)

**Comment by DaveBenham** [comment]
I can't tell if you were intentionally being sarcastically funny, or if you were serious. If everyone follows your advice to "use a *proper* language", then there would be no reason to develop extended batch. :-/

**Comment by adoxa** [comment]
That's right (to what? all of it :smile:). The initial request was for heap variables, to avoid setlocal's slowdown with a huge environment. The way that was implemented opened the door and Carlos, and now you, have really run with it. Maybe if it was just a single exe (or two, 32- and 64-bit), I'd be more inclined, but Carlos wants to support back to Windows 2000, which means I have to find the patches for **61** binaries. So when you say "wouldn't it be nice...", I hear how much work it would take. There's only so much I'm prepared to do to *enhance* batch, not write another language.

**Comment by carlos-montiers** [comment]
I understand all of this: modify a binary is already a headache, thus request a feature that requires many modifications is a lot of headache (multiply by the number of versions that we are supporting). But because you Jason do provide this magnific work in a nice way, sometimes it seems easy. One forget that and ask and ask for features thinking that will not be hard. Really what are you doing is unique.

**Comment by carlos-montiers** [comment]
@DaveBenham what you propose in your stackoverflow article is implement try catch. But I want mentions that the try catch approach in a modern language like golang is not implemented. The approach is check and handle the error after every line that can produce an error. Also exist panic and recover (for rare cases), but all of that are not equivalent to try catch. Try catch as is implemented for example in javascript or java stop the execution flow and jumps your code to the handler block without allow return to the previous line of the block of code where the exceptions ocurrs. Other approach that I see about handling exceptions is not with try catch but using a function as in the win32 c SetUnhandledExceptionFilter, with that you have the possibility of return to the next line of code after the exception ocurrs.
I mentioned this for indicate that for exception/error handler not always the try catch should be the solution.
Also about terminology for example, in golang error is something you can handle, in java an exception can be handled and error not.
This is for indicate that the term error and exception can mean different things. In this issue is mentioned error handling and exception handling.

Currently we have:
```
set __unexisting__
echo Hello
```

And it prints:
```
test.cmd:9: Environment variable __unexisting__ not defined
Hello
```
For me that are error that are implicit handled by CMD printing the error (EB add file and the line number) and continue.
Thus in that sense batch have "errors", and the "exception" is not a thing that batch can thrown because is something that not exist. I understand your usage of "exception" as an instruction for stop the execution of the block of batch code with a message, and your try catch instructions are like supervisors of the last error code of the called functions, in any case is not possible return, in the best case you can log the error.

Thus the hook that you wanted is: when errorlevel is not set to 0 or something is writted to std err, call to goto :eof
Thus is change the behavior of continue on error to stop on error.

But current manual handle of each line for an error is not so bad:
command: mycommmand || (code for handle it)
is something analogous to the golang approach in the sense you control every line for an error.

I think is better continue on error and if you not want that you can manually take care of it, because the lot of work for stop on error really not provides any recovery.

But @adoxa what about ```@errmsg - Get the value of the most recent error message. This could be useful when stderr is redirected to nul```
Is hard of implement it, requires new offsets ?
